spring:
   application:
      name: author-catalog-service
   h2:
      console:
        enabled: true
     
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost

server:
   port: 8081

logging:
  file: D:/impetus/spring/author.log